### ISSUE TITLE
Create Automatic Testing for Simulation Checklist

### ISSUE THREAD

**Issue by Tyronitar** [IanFooMZ/SonyBayerFilter#31]

**Comment by Tyronitar** [comment]
General list of things to test:

## More Important
- [ ] Check Device is being created properly
- [ ] Check sources are being assigned to FoMs correctly
- [ ] Check Optimizer and Optimization are being initiated correctly
- [ ] Check jobs are being created correctly
- [ ] Check that different version of simulations are being created correctly from base sim
- [ ] Check fields are being pulled correctly
- [ ] Check FoMs are being calculated correctly
- [ ] Check gradients are being calculated correctly
    - [ ] Test on a simple math function like absolute value for uniformity
- [ ] Check device is being perturbed by gradient correctly
    - [ ] Test MSE with a 2D Gaussian and use autograd
- [ ] Check overall FoM and gradient are being summed together correctly (weights)

## Less Important
- [ ] First check partitioning is working (E-field segmentation etc.)
- [ ] Make sure device is only being perturbed by small amounts each time
- [ ] Check one FoM (spatial focusing)
- [ ] Check two simultaneous FoMs (spatial focusing)
- [ ] Check two either-or FoMs (polarization sorting)
- [ ] Implement performance weighting
- [ ] Implement spectral FoMs
- [ ] Implement spectral weighting
- [ ] Check restart capability and history
- [ ] Lateral feature size for blurring

**Comment by Tyronitar** [comment]
Finished testing all of the "more important" checks, although there aren't automated tests for optimizations yet.
